services:
  # Backend API Service
  - type: web
    name: elca-blockbusters-api
    env: python
    plan: starter
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: OPENAI_API_KEY
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: XAI_API_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: elca-blockbusters-db
          property: connectionString
    autoDeploy: true
    
  # Frontend Service  
  - type: web
    name: elca-blockbusters-frontend
    env: node
    plan: starter
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm start
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: NEXT_PUBLIC_API_URL
        value: https://elca-blockbusters-api.onrender.com
    autoDeploy: true

databases:
  - name: elca-blockbusters-db
    databaseName: elca_blockbusters
    user: elca_user
    plan: starter
